application:
  section-titles: Java Comprehension,Company Values,Distributed Systems Understanding,Integration
    Tests Comprehension,Automation Tools,Regression Testing,System Design Principles,Cloud
    Infrastructure and Services,Microservices Architecture,Security Best Practices,Frontend
    Technologies,Database Design and Optimization,DevOps and CI/CD Pipelines,Data
    Structures and Algorithms,Performance Tuning,Scalability Strategies,Code Review
    and Quality Assurance,Agile and Scrum Methodologies,Problem-solving Skills,Project
    Management,Machine Learning Basics,Blockchain Fundamentals,IoT Concepts,Big Data
    Technologies,Mobile Development Essentials,User Experience Design,API Design and
    RESTful Services,Software Development Life Cycle,Business Intelligence,Data Privacy
    and Compliance,Open Source Contributions,Leadership and Team Collaboration
spring:
  application:
    name: isds-service
  data:
    mongodb:
      uri: mongodb+srv://serbantiurbe:gfKlzad6pSyYoVEA@interviewcompanionappcl.0dt0g6v.mongodb.net/?retryWrites=true&w=majority&appName=InterviewCompanionAppCluster
      database: isds
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/springboot-microservice-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          useInsecureTrustManager: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: '8084'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: '1.0'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
    auth:
      converter:
        resource-id: microservice-auth
        principle-attribute: preferred_username